"""добавили признак публикации

Revision ID: 86099398935d
Revises: 
Create Date: 2021-07-09 22:07:17.418856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86099398935d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('is_published', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'is_published')
    # ### end Alembic commands ###
